import './globals.css'
import type { Metadata } from 'next'
import Link from 'next/link'
import { Inter } from 'next/font/google'
import { GlobalStyles } from './theme'
import Wrapper from './components/wrapper'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <GlobalStyles />
      <body className={inter.className} suppressHydrationWarning={true}>
        {/* <Wrapper>{children}</Wrapper> */}
        <Wrapper>
          <div className='w-screen h-screen flex items-center justify-center'>
            <h1 className='pointer-events-auto space-x-4 underline text-xl'>
              <Link href='/'>page 1</Link>
              <Link href='/01'>page 2</Link>
              <Link href='/02'>page 3</Link>
              <Link href='/03'>page 4</Link>
            </h1>
          </div>
        </Wrapper>
      </body>
    </html>
  )
}
